[package]
name = "vkc-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
vkl = { path = "../vkl" }
log = "0.4.28"
pretty_env_logger = "0.5.0"
shaderc = { version = "0.10", features = ["build-from-source", "prefer-static-linking"] }
bytemuck = "1.24.0"
