[package]
name = "test_compute"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/pi4erd/compute-vulkan.git"
publish = false

[dependencies]
log = "0.4.28"
pretty_env_logger = "0.5.0"
vkc-lib = { version = "0.1.0", path = "../../vkc-lib" }
